// <auto-generated />
using System;
using LibraryManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LibraryManagementSystem.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagementSystem.Models.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Author of Harry Potter",
                            Email = "rowling@author.com",
                            Name = "J.K. Rowling"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Author of ASOIAF",
                            Email = "martin@author.com",
                            Name = "George R.R. Martin"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "King of Horror",
                            Email = "king@author.com",
                            Name = "Stephen King"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("integer");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PublishedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            ISBN = "HP001",
                            PublishedYear = 1997,
                            Title = "Harry Potter 1"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            ISBN = "TWK001",
                            PublishedYear = 2010,
                            Title = "The Way of Kings"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            ISBN = "GOT001",
                            PublishedYear = 1996,
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 3,
                            ISBN = "SHIN001",
                            PublishedYear = 1977,
                            Title = "The Shining"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 3,
                            ISBN = "IT001",
                            PublishedYear = 1986,
                            Title = "It"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.Borrowing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BorrowDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("MemberId");

                    b.ToTable("Borrowings");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.Member", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Members");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@library.com",
                            FullName = "Admin User",
                            PasswordHash = "$2b$12$FeQYBH2yasvsubBD4ylbneb8jJsGRUm3RAK9P0wVMNMYd0yZG9hLW",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Email = "john@member.com",
                            FullName = "John Doe",
                            PasswordHash = "$2b$12$FeQYBH2yasvsubBD4ylbneb8jJsGRUm3RAK9P0wVMNMYd0yZG9hLW",
                            Role = "Member"
                        },
                        new
                        {
                            Id = 3,
                            Email = "jane@member.com",
                            FullName = "Jane Doe",
                            PasswordHash = "$2b$12$FeQYBH2yasvsubBD4ylbneb8jJsGRUm3RAK9P0wVMNMYd0yZG9hLW",
                            Role = "Member"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.MemberProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MemberId")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MemberId")
                        .IsUnique();

                    b.ToTable("MemberProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Admin HQ",
                            Bio = "Systems Admin",
                            MemberId = 1,
                            Phone = "123456789"
                        },
                        new
                        {
                            Id = 2,
                            Address = "John's Street",
                            Bio = "Avid Reader",
                            MemberId = 2,
                            Phone = "987654321"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Jane's Street",
                            Bio = "Student",
                            MemberId = 3,
                            Phone = "456789123"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.Book", b =>
                {
                    b.HasOne("LibraryManagementSystem.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.Borrowing", b =>
                {
                    b.HasOne("LibraryManagementSystem.Models.Book", "Book")
                        .WithMany("Borrowings")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryManagementSystem.Models.Member", "Member")
                        .WithMany("Borrowings")
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.MemberProfile", b =>
                {
                    b.HasOne("LibraryManagementSystem.Models.Member", "Member")
                        .WithOne("Profile")
                        .HasForeignKey("LibraryManagementSystem.Models.MemberProfile", "MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.Author", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.Book", b =>
                {
                    b.Navigation("Borrowings");
                });

            modelBuilder.Entity("LibraryManagementSystem.Models.Member", b =>
                {
                    b.Navigation("Borrowings");

                    b.Navigation("Profile")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
